### ISSUE TITLE
About Source Property issue

### ISSUE THREAD

**Issue by chen19941018** [kakone/VLC.MediaElement#1]
I use this for Internet video stream, but the stream is flv extension. And the flv are segmented. So it have some issue for get all the segmentation. I find that I only can get the first segmentation, then it will end. Can you modify the Source like MS.MediaElment, it can load all the segmentation. Ty, Haha .

**Comment by kakone** [comment]
I can't do anything to resolve the problem in this control. The work must be done in VLC. You can try with the [VLC app](https://www.microsoft.com/fr-fr/store/p/vlc/9nblggh4vvnh) and, if it doesn't work, create a post in this [page](https://code.videolan.org/videolan/vlc-winrt/issues).
