### ISSUE TITLE
RTSP video feed from raspberry pi freezing

### ISSUE THREAD

**Issue by Spaceman0Spiff** [kakone/VLC.MediaElement#12]
Hi!

I am trying to play a simple RTSP video stream across Ethernet from a raspberry pi.

On the raspberry pi, this command is being run (I am using VLC to create the stream):
`raspivid -o - -t 0 -hf -w 640 -h 360 -fps 25 | cvlc -vvv stream:///dev/stdin --sout '#rtp{sdp=rtsp://:8554}' :demux=h264`

The UWP program is looking here:
`<vlc:MediaElement HardwareAcceleration="True" Source="rtsp://169.254.49.188:8554/"> </vlc:MediaElement>`

This works fine for about 2-3 seconds, then the video freezes. It also is working correctly in the VLC player.

Do you know what might be causing this issue / how I might trouble shoot it?

Please let me know if there is any additional info you may need. I am a video streaming novice so any advise would be awesome.

Thank you!

**Comment by kakone** [comment]
> It also is working correctly in the VLC player.

In which VLC player ? [VLC for UWP](https://www.microsoft.com/store/p/vlc/9nblggh4vvnh) ? [VLC Desktop 2.2.4](http://www.videolan.org/vlc/) or [VLC Desktop 3.0](http://nightlies.videolan.org/build/win64/last/) ?

**Comment by Spaceman0Spiff** [comment]
Thanks for the quick response!

> In which VLC player ? VLC for UWP ? VLC Desktop 2.2.4 or VLC Desktop 3.0 ?

VLC Desktop 3.0 is working for me.

Upon further investigation this afternoon, the feed isn't actually freezing so much as hanging. It can hang for upwards of 10 seconds, so when I thought the video had frozen, I must not have given it enough time to obtain a full connection (sorry, novice at developing with video streams).

So, I don't think this is an issue for your package, but rather more likely something happening on my end. Is there an ability to log what the player is receiving/ see why it would hang after connecting and working properly for the first few seconds?

Thanks again for the help

**Comment by Spaceman0Spiff** [comment]
After continuing experimenting with different streaming protocols , my issue seemed to lie with using rtsp. Using http seems to work much better without any hangs or freezing. So it appears the issue did not lie at all with this library, apologies for the misinterpretation.
