### ISSUE TITLE
no file time position?

### ISSUE THREAD

**Issue by hamza87** [kakone/VLC.MediaElement#14]
Hi!
I want to access the position of the file playing but I can't find any property for it. The MediaElement has a Position property in 'MediaElement.PlaybackSession.Position' publicly accessible. Is there a way to retrieve it in your custom control? thanks.

**Comment by hamza87** [comment]
also is there a way to access all the public properties of the underlying MediaElement? that way we'd have the basic stuff and the bonus elements brought by your control.

**Comment by kakone** [comment]
I'm adding the Position property (but I have a strange bug, two way binding doesn't seem to work in Windows Runtime Components).

Otherwise, you are right, I think I will change the modifier of the underlying MediaPlayer property from private to public.

**Comment by kakone** [comment]
The Position property was added in [version 0.9.11](https://www.nuget.org/packages/VLC.MediaElement/0.9.11) and the getter of the underlying MediaPlayer property is now public.
