### ISSUE TITLE
Support for http/ts:// uri

### ISSUE THREAD

**Issue by roman-76** [kakone/VLC.MediaElement#15]
I'm getting url from external service that starts with "http/ts://" protocol.
vlc media player successfully plays that url but Vlc MediaElement fails.

AFAIU, call to 
`Uri.TryCreate(source, UriKind.RelativeOrAbsolute, out location)`
in MediaElement.cs fails to parse that uri.

Could you please add support for it?

**Comment by kakone** [comment]
> vlc media player successfully plays that url

[VLC for UWP](https://www.microsoft.com/store/p/vlc/9nblggh4vvnh) or the desktop version of VLC ?
Even if the `Uri.TryCreate` returns false, the source is passed to the underlying mediaplayer, it should work.

**Comment by roman-76** [comment]
You are right, VLC for UWP doesn't support that either.
