### ISSUE TITLE
Save video file (.mkv, .avi, .mp4...)

### ISSUE THREAD

**Issue by cahernanz** [kakone/VLC.MediaElement#16]
Hi and thanks for your helping. Do you know how to save in a video file the content I am playing or streaming using LibVlcx and Vlc.MediaElement?

Thanks a lot!

**Comment by kakone** [comment]
I don't think it's possible to record the video for the moment (that's why the option doesn't exist in [VLC for UWP](https://www.microsoft.com/store/p/vlc/9nblggh4vvnh)).
