### ISSUE TITLE
How can I change the template?

### ISSUE THREAD

**Issue by panzur** [kakone/VLC.MediaElement#17]
Is there way to change the template? Can you provide an example?

**Comment by kakone** [comment]
Copy the vlc:MediaTransportControls default style into a ResourceDictionary in your project, and edit it like you want.
Give the Style an x:Key value to identify it, like this :
```
<Style TargetType="vlc:MediaTransportControls" x:Key="myTransportControlsStyle">
    <!-- Style content ... -->
</Style>
```
Add a vlc:MediaElement with vlc:MediaTransportControls to your UI.
Set the Style property of the MediaTransportControls element to your custom Style resource, as shown here :
```
<vlc:MediaElement AreTransportControlsEnabled="True">
    <vlc:MediaElement.TransportControls>
        <vlc:MediaTransportControls Style="{StaticResource myTransportControlsStyle}" />
    </vlc:MediaElement.TransportControls>
</vlc:MediaElement>
```

**Comment by ibhabc** [comment]
@kakone  
Does your answer can be solution to this issue ?
**[Add docs on how to custom style/bind the LibVLCSharp.Forms MediaElement](https://code.videolan.org/videolan/LibVLCSharp/-/issues/309)**
