### ISSUE TITLE
MPEG4 & H264 streaming

### ISSUE THREAD

**Issue by cahernanz** [kakone/VLC.MediaElement#18]
Hi!, Finally I found the way to stream for my ip camera MJPEG way, but if I change the encoder to MPEG4 or H264 to play the streaming, I see nothing. Could be problem of codecs or do you think I am doing something wrongly?

Thanks in advance!

**Comment by kakone** [comment]
VLC don't use the Windows codecs. I think there must be a bug in libVLC or with your graphic card but it doesn't depend on the VLC.MediaElement control.
