### ISSUE TITLE
RTSP Authentication Support?

### ISSUE THREAD

**Issue by TheOriginalAppStar** [kakone/VLC.MediaElement#2]
The UWP VLC app in the windows store supports RTSP. Does the VLC.MediaElement support RTSP? I can't connect to an RTSP url.

**Comment by TheOriginalAppStar** [comment]
Turns out I can connect to an RTSP live stream. What doesn't work is connecting to an RTSP stream that requires authentication. I've tried inserting credentials into the url via this convention: rtsp://[Username]:[Password]@[IP]:[Port], but it still doesn't work. (FYI, the log says this convention is deprecated). How can I provide my credentials to the stream?

**Comment by kakone** [comment]
With VLC command line (https://wiki.videolan.org/VLC_command-line_help/), we can add these credentials with rtsp-user and rtsp-pwd options. I just created an Options property on the MediaElement to add options to the media. You must define this property before setting the source. Try to add rtsp-user and rtsp-pwd to this options dictionary, perhaps it will works.

**Comment by TheOriginalAppStar** [comment]
Thanks for the quick reply! Unfortunately adding the user and pwd options didn't work. I even set the dialog handlers on the Instance but ShowLoginDialog is never invoked. It's strange that it works in the VLC Universal app but not here. I attached a debugger to the VLC Universal app and you can clearly see live555 returns "authentication failed". However, it then attempts to authenticate with my user and successfully opens the stream. My app never does that; instead live555 returns "connection error -10057" and vlc attempts some alternative methods which also fail. None of them seem to try and authenticate. Is it possible there is a missing configuration or even libVLCX is out of date?

Working VLC Universal app log:
`core input debug: Creating an input for 'rtsp://x.x.x.x:x/videoMain'
core input debug: using timeshift granularity of 50 MiB
core input debug: using default timeshift path
core input debug: `rtsp://x.x.x.x:x/videoMain' gives access `rtsp' demux `any' path `x.x.x.x:x/videoMain'
core input source debug: creating demux: access='rtsp' demux='any' location='x.x.x.x:x/videoMain' file='\\x.x.x.x:x\videoMain'
core demux debug: looking for access_demux module matching "rtsp": 6 candidates
live555 demux debug: version 2016.07.19
live555 demux debug: authentication failed
core keystore debug: looking for keystore module matching "any": 3 candidates
core keystore debug: using keystore module "file"
live555 demux debug: retrying with user=TheOriginalAppStar
core keystore debug: removing module "file"
live555 demux debug: RTP subsession 'video/H264'
core input debug: selecting program id=0
live555 demux debug: RTP subsession 'audio/PCMU'
live555 demux debug: setup start: 0.000000 stop:0.000000
live555 demux debug: We have a timeout of 65 seconds
live555 demux debug: play start: 0.000000 stop:0.000000
core demux debug: using access_demux module "live555"
core packetizer debug: looking for packetizer module matching "any": 24 candidates
h264 packetizer debug: found NAL_SPS (sps_id=0)
h264 packetizer debug: found NAL_PPS (pps_id=0 sps_id=0)
core packetizer debug: using packetizer module "h264"
core decoder debug: looking for decoder module matching "any": 43 candidates
avcodec decoder debug: CPU flags: 0x000fd3db
avcodec decoder debug: allowing 1 thread(s) for decoding
avcodec decoder debug: codec (h264) started
core decoder debug: using decoder module "avcodec"
core decoder debug: looking for decoder module matching "any": 43 candidates
g711 decoder debug: samplerate:8000Hz channels:1
core decoder debug: using decoder module "g711"
core demux meta debug: looking for meta reader module matching "any": 2 candidates
lua demux meta debug: Trying Lua scripts in C:\Users\xxxxx\AppData\Local\Packages\VideoLAN.VLC_paz6r1rewnh0a\LocalState\vlc\lua\meta\reader
core demux meta debug: no meta reader modules matched
core input debug: `rtsp://x.x.x.x:x/videoMain' successfully opened
core input debug: Buffering 0%`

Non-working MediaElement log:
`[VLC Debug] [core] (../../src/input/input.c:295) Creating an input for 'rtsp://x.x.x.x:x/videoMain'
[VLC Debug] [core] (../../src/input/es_out_timeshift.c:340) using timeshift granularity of 50 MiB
[VLC Debug] [core] (../../src/input/es_out_timeshift.c:384) using default timeshift path
[VLC Debug] [core] (../../src/input/input.c:2414) `rtsp://x.x.x.x:x/videoMain' gives access `rtsp' demux `any' path `x.x.x.x:x/videoMain'
[VLC Debug] [core] (../../src/input/demux.c:222) creating demux: access='rtsp' demux='any' location='x.x.x.x:x/videoMain' file='\\x.x.x.x:x\videoMain'
[VLC Debug] [core] (../../src/modules/modules.c:231) looking for access_demux module matching "rtsp": 6 candidates
[VLC Debug] [live555] (../../modules/access/live555.cpp:332) version 2016.07.19
[VLC Debug] [live555] (../../modules/access/live555.cpp:662) connection error -10057
[VLC Error] [live555] (../../modules/access/live555.cpp:411) Failed to connect with rtsp://x.x.x.x:x/videoMain
[VLC Debug] [core] (../../src/modules/modules.c:321) no access_demux modules matched
[VLC Debug] [core] (../../src/input/access.c:92) creating access: rtsp://x.x.x.x:x/videoMain
[VLC Debug] [core] (../../src/input/access.c:105)  (path: \\x.x.x.x:x\videoMain)
[VLC Debug] [core] (../../src/modules/modules.c:231) looking for access module matching "rtsp": 23 candidates
[VLC Debug] [satip] (../../modules/access/satip.c:630) try to open 'rtsp://x.x.x.x:x/videoMain'
[VLC Debug] [satip] (../../modules/access/satip.c:661) connect to host 'x.x.x.x'
[VLC Debug] [core] (../../src/network/tcp.c:121) net: connecting to x.x.x.x port x
[VLC Error] [core] (../../src/network/tcp.c:195) connection failed: Access denied
[VLC Error] [satip] (../../modules/access/satip.c:665) Failed to connect to RTSP server x.x.x.x:x
[VLC Debug] [core] (../../src/network/tcp.c:121) net: connecting to x.x.x.x port x
[VLC Error] [core] (../../src/network/tcp.c:195) connection failed: Access denied
[VLC Error] [access_realrtsp] (../../modules/access/rtsp/access.c:86) cannot connect to x.x.x.x:x
[VLC Error] [core] (../../src/interface/dialog.c:375) Connection failed
[VLC Error] [core] (../../src/interface/dialog.c:376) VLC could not connect to "x.x.x.x:x".
[VLC Debug] [access_realrtsp] (../../modules/access/rtsp/access.c:186) could not connect to: x.x.x.x:x/videoMain
[VLC Debug] [core] (../../src/modules/modules.c:321) no access modules matched
[VLC Error] [core] (../../src/interface/dialog.c:375) Your input can't be opened
[VLC Error] [core] (../../src/interface/dialog.c:376) VLC is unable to open the MRL 'rtsp://x.x.x.x:x/videoMain'. Check the log for details.`

**Comment by kakone** [comment]
If it works in the VLC Universal app, we must be able to make it work. In the VLC Universal app, it displays a login dialog box ?

**Comment by apetkovic** [comment]
It works both ways as expected in the VLC UWP App.
1. With credentials in the url. No login box; stream just starts to play. (deprecated)
2. No credentials in the url. Login box appears. After login stream starts to play.

I've tried both ways in the MediaElement app. I'm trying to understand why the logs are different for live555. Why does the same url return "connection error -10057" on my app, but VLC App returns "authentication failed" and then automatically attempts to authenticate?

**Comment by kakone** [comment]
Very strange, I don't know what's missing. I'm browsing the [source code of the VLC app](https://code.videolan.org/videolan/vlc-winrt/tree/master) to find the difference.

**Comment by TheOriginalAppStar** [comment]
I pulled down the VLC Universal app source to rule out the possibility of some strange build issue on my machine causing the problem. The local build VLC app ran just like the one downloaded from the store and played the stream properly. (Btw, I really appreciate the simplicity of your libVLC nuget package even more so after going though the build process).

This is a long shot... I noticed VLC is using async and await to make sure the player Instance is ready before attempting to play any media. Now that the KeyStore file was added to init; is it possible the keystore isn't fully loaded before playing the stream and therefore VLC is skipping authentication logic?

**Comment by TheOriginalAppStar** [comment]
Found the issue! VLC requires the "privateNetworkClientServer" Capability in the app manifest for authentication to work. I also added the "backgroundMediaPlayback" capability for good measure. Thanks for your help and putting this project out there!

**Comment by kakone** [comment]
Great !
I think it's RTSP that requires privateNetworkClientServer capability because HTTP authentication works great without it.
I'm adding some events to manage the login dialog event.

**Comment by kakone** [comment]
In [version 0.9.10](https://www.nuget.org/packages/VLC.MediaElement/0.9.10), you can now use rtsp://user:pass@xyz directly.
