### ISSUE TITLE
Unable to Programmatically Add Instances

### ISSUE THREAD

**Issue by RichieRogers** [kakone/VLC.MediaElement#20]
I'm not sure if you can create VLC mediaelements programmatically, but i'm certainly unable to.
If i create a number of VLC mediaelements in the designer they run perfectly.
However, if i create them programmatically the app always errors with "Object reference not set to an instance of an object." 

                    VLC.MediaElement camera = new VLC.MediaElement();
                    camera.Name = "cctv" + item.GLOBALCCTVCAMERAID.ToString();
                    camera.AreTransportControlsEnabled = false;
                    camera.HardwareAcceleration = true;
                    camera.AutoPlay = false;
                    camera.Height = item.ThumbHeight;
                    camera.Width = item.ThumbWidth;
                    camera.Source = item.CameraURL.Replace("&", "&amp;");

                    //add to panel
                    wrapMain.Children.Add(camera);

This code is the inner part of a loop that put a variable number of mediaelements into a wrap panel.
I have tried removing everything except creating and adding the control, as well as adding them directly to the grid page to rule them out.

So, I suspect one of the following:
1. You can't use this control programmatically
2. I'm creating the instance of the control incorrectly
3. There's a bug in the VLC mediaelement control

Any help much appreciated,
Richie

**Comment by kakone** [comment]
I vote for the third option ;)

Fixed in version [0.9.13](https://www.nuget.org/packages/VLC.MediaElement/0.9.13).

**Comment by RichieRogers** [comment]
Thanks for the prompt reply and fix.
I will try it out tonight.

Richie

**Comment by RichieRogers** [comment]
Tried it and app doesn't crash any more.
However i can only get the multiple instances to display anything if i do a screen resize once (it only then shows them once and if i choose different sources resizing screen doesn't make them show).
Not sure i'm explaining myself very well here :(
Is there some sort of refesh/redraw of the controls required?

Richie

**Comment by RichieRogers** [comment]
Actually, ignore some of that.
I have an app that pulls up four cameras from one location and four cameras from a second location (the locations are chosen from a combobox.
If I select the location from the combobox it then loads the instances into a wrap panel.
However, the really weird thing is that the instances only appear if i go back to the combobox and click the dropdown arrow (ie just to show the list, not actually change the item).
So it looks like the drawing of the combobox content causes a refresh (?) of the vlc mediaelements.

Any ideas?

Richie
