### ISSUE TITLE
Further Issue Related to Multiple Programmatically Added Instances

### ISSUE THREAD

**Issue by RichieRogers** [kakone/VLC.MediaElement#21]
Hi,
Thanks for promptly fixing my earlier reported bug.
However, this has now raised a second issue.
I have a UWP app with a combobox to select 4 CCTV cameras from one of two locations.
If I select one of the locations from the combobox no instances of VLC mediaelement appear.
If I then click on the arrow on the combobox to display the items (NOT actually click on an item) it then proceeds to show the four programmatically generated VLC mediaelements.
Weirdly, though if I also create a second combobox with just two dummy items in (that has no events or calls to any functions) i can then click on the arrow to display the items and it will also cause the four VLC mediaelements to appear.
I am, therefore, concluding that there is another bug in the VLC mediaelement relating to how it is rendered and that whatever a combobox "does" when displaying its items is then triggering the rendering of the VLC mediaelement.

Hopefully this is an easy fix.

Thanks,
Richie

**Comment by kakone** [comment]
To be able to correct it quickly, It would be nice if you could share a sample app that reproduces the problem.

**Comment by RichieRogers** [comment]
Thanks. Will knock something up

Richie

**Comment by RichieRogers** [comment]
Hi,
I've upload a simple VS2015 project to:
http://rogersuk.me.uk/UWP_VLC-MediaElement_Test1.zip

If you select from the combobox the "screens" only appear when you then click on the combobox again to display the options

Thanks
Richie

**Comment by kakone** [comment]
Fixed in [version 0.9.15](https://www.nuget.org/packages/VLC.MediaElement/0.9.15).

**Comment by RichieRogers** [comment]
Oh, excellent.
I will try this over the weekend.
Thanks for all your work on this brilliant control.

Richie

**Comment by RichieRogers** [comment]
Just to let you know that this now works brilliantly.
Thanks for all your help,
Richie
