### ISSUE TITLE
Error When Trying to Open New File in Existing Instance

### ISSUE THREAD

**Issue by RichieRogers** [kakone/VLC.MediaElement#22]
Hi,
I'm using a FileOpenPicker to load a VLC mediaelement, which works fine.
However, if i then try to load a new video into the VLC mediaelement I got the below error:
Object reference not set to an instance of an object.

XAML:
<VLC:MediaElement x:Name="vlcPlay" Margin="0,125,0,0" VerticalAlignment="Stretch" HorizontalAlignment="Stretch" AreTransportControlsEnabled="True" HardwareAcceleration="True">
            <VLC:MediaElement.TransportControls>
                <VLC:MediaTransportControls ControlPanelOpacity="0.8" IsStopButtonVisible="True" IsFullWindowButtonVisible="True" />
                
            </VLC:MediaElement.TransportControls>
        </VLC:MediaElement>

C#:
private const string FILE_TOKEN = "{1BBC4B94-BE33-4D79-A0CB-E5C6CDB9D107}"; // GUID in registry format
//open file picker with filters for video files
            Windows.Storage.Pickers.FileOpenPicker filePicker = new FileOpenPicker();
            filePicker.ViewMode = PickerViewMode.Thumbnail;

            //define filters based on video files VLC can support
            foreach(string fileext in Videofiles.Split(','))
            {
                filePicker.FileTypeFilter.Add("." + fileext);
            }

            var selectedFile = await filePicker.PickSingleFileAsync();
            if(selectedFile != null)
            {
                StorageApplicationPermissions.FutureAccessList.AddOrReplace(FILE_TOKEN, selectedFile);
                vlcPlay.Source = null;
                vlcPlay.Source = $"winrt://{FILE_TOKEN}";
                vlcPlay.AreTransportControlsEnabled = true;
                vlcPlay.TransportControls.AutoHide = true;

                //hide info textblock
                canAudioFileInfo.Visibility = Visibility.Collapsed;
            }

I had thought that setting the source to null prior to loading a new file would "clear" any existing file, but guessing not.
Do i need to somehow "reset" the VLC mediaelement or am I going to have to try and move the control to some sort of usercontrol popup, so it will be initialised each time?

Richie

**Comment by kakone** [comment]
It's a bug, it will be fixed in version [0.9.14](https://www.nuget.org/packages/VLC.MediaElement/0.9.14).

You must set the Source to null because, otherwise, the Source property doesn't change (the string value is the same, always $"winrt://{FILE_TOKEN}") and nothing happens.

**Comment by RichieRogers** [comment]
Thanks.
Sorry I keep (forgive the pun) bugging you.
It really is an excellent control.

Richie
