### ISSUE TITLE
MediaTransportControls won't hide after Touch Input

### ISSUE THREAD

**Issue by nograx** [kakone/VLC.MediaElement#23]
Hi,

thanks again for These great controls.

if I add Content to the TransportControls (vlc:MediaTransportControls.Content) and use the TransportControls with Touch Input the TransportControls won't get hidden sometimes. They are getting always hidden on Mouse/Keyboard/Controller Input.

Kind regards,
Peter

**Comment by nograx** [comment]
Any news on this?

**Comment by kakone** [comment]
When you touch your content, the transport controls (and your content) will not hide, you must touch an empty space outside your content to hide them. It's the same behavior with the mouse, if your put your mouse cursor on your content, it will not hide. But, I think it's not that what you want ?

**Comment by nograx** [comment]
If I use the mouse and click on playback controls, the transport controls (and my content) will hide. But if I use touch input it won't hide automatically.
