### ISSUE TITLE
Creators Update PIP Mode (CompactOverlay mode)

### ISSUE THREAD

**Issue by nograx** [kakone/VLC.MediaElement#24]
Just a short question. Do you plan du integrate the Picture-In-Picture Mode introduced by the Creators Update?

==> https://blogs.msdn.microsoft.com/universal-windows-app-model/2017/02/11/compactoverlay-mode-aka-picture-in-picture/

**Comment by kakone** [comment]
Yes, when I have time, I will add the PIP mode. I must also ameliorate the fullscreen mode.

**Comment by kakone** [comment]
Properties IsCompactOverlayModeButtonVisible and IsCompactOverlayModeButtonEnabled added on MediaTransportControls class, with ViewModeChanging and ViewModeChanged events.
Like the fullscreen fonctionnality, the full app goes in compact overlay mode, not only the video player.
