### ISSUE TITLE
muteToggle is buggy

### ISSUE THREAD

**Issue by touseefbsb** [kakone/VLC.MediaElement#25]
I tried vlcmedia element with my uwp app and I tried the togglemute() method to mute and unmute the media player. once I muted it with this method, it got muted but never got unmuted again. Now I even made a new app and reinstalled the package from nuget and didnt even touch the mute method but it is still mute and every video played in vlc media element is sound less now :/ it made some changes I guess to my system and is now causing problem because I cant hear any thing in vlc media element at all

**Comment by kakone** [comment]
Yes, it's a bug in libVLC, that's why I don't use this method. I use the setVolume method that works well. If you use the IsMuted property on the VLC.MediaElement, it should work.

**Comment by touseefbsb** [comment]
yes Ismuted works perfect thanks :)
