### ISSUE TITLE
too much memory consumption.

### ISSUE THREAD

**Issue by touseefbsb** [kakone/VLC.MediaElement#26]
I created a simple UWP app with no features at all and only a vlc media element to play a normal video and according to disagnostic tools of visual studio it is consuming upto 250 MB of memory. This will not be fine specially if the app runs on windows 10 phone. I hope you can update the nuget package and it may consume less memory than before, Thanks in advance :) This might be a useful enhancement to the package .

**Comment by kakone** [comment]
My library is just a control over libVLC, I can't handle the memory consumption of VLC.
