### ISSUE TITLE
no media failed event handler

### ISSUE THREAD

**Issue by touseefbsb** [kakone/VLC.MediaElement#29]
I am having an error "canot open mrl, check log for details" and log file is also empty so I need to figure out the problem, and for that I need to handle media failed event like in normal media element but its not there. There is no media failed event on VLCMediaElement :/

**Comment by kakone** [comment]
Yes, I will add this event as soon as possible.

**Comment by touseefbsb** [comment]
When you do please also add media opened and closed and other related events.

**Comment by touseefbsb** [comment]
this feature was supposed to come with version 0.9.18 , this version is already released, do we have this event handler now?

**Comment by kakone** [comment]
No, I didn't add this event yet.

**Comment by touseefbsb** [comment]
oh alright
