### ISSUE TITLE
how to create custom inherited control from vlc media element

### ISSUE THREAD

**Issue by touseefbsb** [kakone/VLC.MediaElement#30]
I want to create a custom control inherited from vlc media element because I want to add some custom buttons to the controls, but when I try to inherit class "vlc.MediaTransportControls" it gives me error because this class is sealed so I cannot create a custom transport control, is there any work around for it ? Thanks

**Comment by kakone** [comment]
Yes, you are right. As it's a Windows Runtime Component, you can't inherit from the MediaElement or MediaTransportControls classes. The first workaround would be to remove the sealed keyword and to compile as a class library (perhaps I could do a second nuget package for this).
Other workaround (ugly) : add your custom buttons in another button bar in the Content property of the MediaTransportControls.

**Comment by touseefbsb** [comment]
yeah I did the other work around it works but it doesnt look so good for the user, so 1st work around would be the best, can you please do that and update the respository and nuget package? or perhaps you can guide me how to do it quickly? I mean I am using nuget package right now, but I can download the repo directly from here and if I just remove the sealed keyword from the class will it work fine ? or are there any more steps to follow?

**Comment by kakone** [comment]
I created a new package : https://www.nuget.org/packages/VLC.MediaElement.ClassLibrary
Add this package instead of the Windows Runtime Component package and you should be able to create some custom media transport controls.

**Comment by touseefbsb** [comment]
thnks a lot

**Comment by touseefbsb** [comment]
I just tried to create a simple inherited custom transport control following Microsoft docs and I got a null refrence exception on many objects within VLC namespace. have you tested the class library package to create custom control? if yes then can you please provide me a very basic and simple sample to do so?

**Comment by kakone** [comment]
Yes, I tested it quickly. Here is a sample project : [App1.zip](https://github.com/kakone/VLC.MediaElement/files/1049555/App1.zip) (it's follow [the documentation](https://docs.microsoft.com/en-US/windows/uwp/controls-and-patterns/custom-transport-controls#create-a-derived-control) using this [Generic.xaml](https://github.com/kakone/VLC.MediaElement/blob/master/VLCMediaElement/Themes/Generic.xaml) file).

**Comment by touseefbsb** [comment]
I tried to compile the sample project you provided but its giving very basic compile time errors for unknown reasons, for example its not even recognizing System namespace that is why it has a lot of compile time errors. Also I checked the refrence node, there is no refrence for vlc media element class library nuget package or no second project of the class library to refrence to.

**Comment by kakone** [comment]
Right click on the Solution and choose 'Restore Nuget Packages', it must restore the VLC.MediaElement.ClassLibrary nuget package and you will see it in the References.

**Comment by touseefbsb** [comment]
Error occurred while restoring NuGet packages: Unable to load package 'Microsoft.Net.Native.SharedLibrary-x64'.		

Failed to download package 'Microsoft.Net.Native.SharedLibrary-x64.1.6.1' from 'https://api.nuget.org/v3-flatcontainer/microsoft.net.native.sharedlibrary-x64/1.6.1/microsoft.net.native.sharedlibrary-x64.1.6.1.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/microsoft.net.native.sharedlibrary-x64/1.6.1/microsoft.net.native.sharedlibrary-x64.1.6.1.nupkg' has timed out after 100000ms.

**Comment by touseefbsb** [comment]
these are the errors I recieve when I try to restore nuget packages.

**Comment by kakone** [comment]
Strange error, you seems to have a problem to access nuget.org.
Did you try this workaround ? https://stackoverflow.com/a/44038629

**Comment by touseefbsb** [comment]
i tried it also failed, can you please provide me a project where I dont need to restore packages?
