### ISSUE TITLE
How to handle TimedTextSource for .srt subs?

### ISSUE THREAD

**Issue by touseefbsb** [kakone/VLC.MediaElement#31]
Is there a way to include external .srt ( subtitle / closed caption files ) with a video. I mean in normal uwp media element it is done by TimedTextSource through mediaSource, but here source of media is just a path or string , in this case ( vlc media element ) how can we handle this scenario? Thanks

**Comment by kakone** [comment]
I'm working on it, it will be available soon.

**Comment by touseefbsb** [comment]
thanks :)

**Comment by kakone** [comment]
Use the new [MediaSource](https://github.com/kakone/VLC.MediaElement/blob/master/VLCMediaElement/MediaSource.cs) dependency property on the MediaElement class.
There is an example in the [sample app](https://github.com/kakone/VLC.MediaElement/blob/master/SampleApp/MainViewModel.cs).
