### ISSUE TITLE
Unable to Open RTSP

### ISSUE THREAD

**Issue by StraightfaceStudios** [kakone/VLC.MediaElement#32]
Not sure what debugging I can perform but I have an RTSP server running on one machine.   And when I open it in VLC Windows Store it works. (e.g. rtsp://192.168.94.55:9001/stream)  I see the connection open on the rtsp server and close when vlc closes.   It also works in the desktop application.  But for some reason MediaElement in VLC does not work.  "VLC is unable to open the MRL 'rtsp://192.168.94.55:9001/stream'. Check the log for details."

Any ideas on why it would work in VLC Desktop/Windows Store/Phone but not in Media Element? Things I could try on my end to help debug?   It's a bit of a black box.

**Comment by StraightfaceStudios** [comment]
Ok.  I tried connecting to the device through Wifi and it does work/stream.   So perhaps there is a network interface resolution happening in the full VLC that's failing in the media element when you have multiple network interfaces.   Oddly though if I try a web stream through the ethernet network it does work.   So local rtsp streaming doesn't work over ethernet but does work over the wifi adapter.

**Comment by kakone** [comment]
Strange bug, I have multiple network interfaces on my computer and local rstp streaming works well over ethernet. Can you try giving all network capabilities to your application : Private network of course, but also Internet Client/Server capability.
