### ISSUE TITLE
Horizontal Scaling doesn't center object in windowed mode

### ISSUE THREAD

**Issue by StraightfaceStudios** [kakone/VLC.MediaElement#33]
If you have a video playing and you do a bidirectional corner scaling of the window, the video player will rescale properly.  If however you simply expand the window the player will remain on the far left side until you perform a vertical scale and then it will recenter the video to fill the window.   It appears the callback for horizontal scaling only triggers on a vertical scale.

**Comment by kakone** [comment]
Yes, it's a bug in libvlcX.Instance.UpdateSize method, the problem appears also in VLC for UWP.
