### ISSUE TITLE
Your input can't be opened - Access denied

### ISSUE THREAD

**Issue by cjscholten** [kakone/VLC.MediaElement#34]
When I try to open the stream of an IP camera in VLC.MedaElement I get the error message
"Your input can't be opened. VLC is unable to open the MRL ...."

The logfile gives a reason for it: Access denied. But same URL works perfectly in my browser or VLC desktop app. Any idea what it could be?

> 
> 18,"None","2017-06-22T22:50:22.0055763","0,0000624","13968","8288","vlcElement","LogMsgVerbose: StringMessage=[core] (../../src/input/access.c:92) creating access: http://192.168.178.59/axis-cgi/mjpg/video.cgi?user=test&pwd=test&fps=1&resolution=1280x800",
> 19,"None","2017-06-22T22:50:22.0056263","0,0000500","13968","8288","vlcElement","LogMsgVerbose: StringMessage=[core] (../../src/input/access.c:105)  (path: \\192.168.178.59\axis-cgi\mjpg\video.cgi)",
> 20,"None","2017-06-22T22:50:22.0056871","0,0000608","13968","8288","vlcElement","LogMsgVerbose: StringMessage=[core] (../../src/modules/modules.c:231) looking for access module matching ""http"": 24 candidates",
> 21,"None","2017-06-22T22:50:22.0094861","0,0037990","13968","692","vlcElement","LogMsgVerbose: StringMessage=[transport] (../../modules/access/http/transport.c:58) resolving 192.168.178.59 ...",
> 22,"None","2017-06-22T22:50:22.0095741","0,0000880","13968","692","vlcElement","LogMsgVerbose: StringMessage=[transport] (../../modules/access/http/transport.c:71) connecting to 192.168.178.59 port 80 ...",
> 23,"None","2017-06-22T22:50:22.0111534","0,0015793","13968","692","vlcElement","LogMsgError: StringMessage=[transport] (../../modules/access/http/transport.c:92) cannot connect to 192.168.178.59 port 80: No error",
> 24,"None","2017-06-22T22:50:22.0154190","0,0042656","13968","8288","vlcElement","LogMsgError: StringMessage=[access] (../../modules/access/http/access.c:228) HTTP connection failure",
> 25,"None","2017-06-22T22:50:22.0155337","0,0001147","13968","8288","vlcElement","LogMsgVerbose: StringMessage=[http] (../../modules/access/http.c:243) querying proxy for http://192.168.178.59/axis-cgi/mjpg/video.cgi?user=test&pwd=test&fps=1&resolution=1280x800",
> 26,"None","2017-06-22T22:50:22.0155858","0,0000521","13968","8288","vlcElement","LogMsgVerbose: StringMessage=[http] (../../modules/access/http.c:249) no proxy",
> 27,"None","2017-06-22T22:50:22.0156367","0,0000509","13968","8288","vlcElement","LogMsgVerbose: StringMessage=[http] (../../modules/access/http.c:274) http: server='192.168.178.59' port=80 file='/axis-cgi/mjpg/video.cgi'",
> 28,"None","2017-06-22T22:50:22.0157033","0,0000666","13968","8288","vlcElement","LogMsgVerbose: StringMessage=[core] (../../src/network/tcp.c:121) net: connecting to 192.168.178.59 port 80",
> 29,"None","2017-06-22T22:50:22.0161876","0,0004843","13968","8288","vlcElement","LogMsgError: StringMessage=[core] (../../src/network/tcp.c:195) connection failed: Access denied",
> 30,"None","2017-06-22T22:50:22.0162650","0,0000774","13968","8288","vlcElement","LogMsgError: StringMessage=[http] (../../modules/access/http.c:688) cannot connect to 192.168.178.59:80",
> 31,"None","2017-06-22T22:50:22.0163198","0,0000548","13968","8288","vlcElement","LogMsgVerbose: StringMessage=[core] (../../src/modules/modules.c:321) no access modules matched",
>

**Comment by kakone** [comment]
Can try giving all network capabilities to your application : Private network but also Internet Client/Server capability.

**Comment by cjscholten** [comment]
You're a life saver. Private networks was indeed the problem. Thanks!
