### ISSUE TITLE
Captions

### ISSUE THREAD

**Issue by cbordeman** [kakone/VLC.MediaElement#36]
Is there a way to display captions?  I need to add a button on the bottom area to enable pulling CC out of a UDP stream.  This works fine with regular VLC on Windows, but don't know how to accomplish here.  Thanks.  Fantastic work on this wrapper, BTW, I was having hell getting libVLC to compile and you saved me so much time!

**Comment by kakone** [comment]
For external subtitle files, use the new [MediaSource](https://github.com/kakone/VLC.MediaElement/blob/master/VLCMediaElement/MediaSource.cs) dependency property on the MediaElement class.
There is an example in the [sample app](https://github.com/kakone/VLC.MediaElement/blob/master/SampleApp/MainViewModel.cs).

**Comment by cbordeman** [comment]
Thanks for the info.  Could you please update the Nuget version?  It's really out of date and the latest seems to work well.

**Comment by kakone** [comment]
The [VLC.MediaElement](https://www.nuget.org/packages/VLC.MediaElement) NuGet package is uptodate.
The [nightly builds](https://nightlies.videolan.org/build/winrt-x86_64/) of libVLC for UWP doesn't seem to work anymore. So, I'm waiting some new nightly builds to update the [libVLCX](https://www.nuget.org/packages/libVLCX/) package.
