### ISSUE TITLE
Failed to assign to property 'VLC.MediaTransportControls.CursorAutoHide'. 

### ISSUE THREAD

**Issue by touseefbsb** [kakone/VLC.MediaElement#37]
this exception occurs on InitializeComponent() in a user control I made, and I am using CustomMediaTransportControls made with vlc media element class library. Note that this error only occurs when I am debugging on a machine with windows 10 anniversay update ( 1607 ) and it doesnt occur when I am using a machine which has windows insider build.
If I remove property "CursorAutoHide" and run without it then it gives another error as follows : 

Failed to assign to property 'VLC.MediaTransportControls.Content

**Comment by touseefbsb** [comment]
is there any progress to solve this bug?

**Comment by touseefbsb** [comment]
@kakone  kindly let me know if there is any progress in this issue, because of this bug we cannot run or target out app on anniversary version of windows 10.

**Comment by kakone** [comment]
I didn't succeed in reproduce the problem. It works well on my machine with Windows 10 Anniversary update. Can you share your code ?

**Comment by touseefbsb** [comment]
actually I tried it with just running the sample app and it crashed so I reported this big at that time. I havent tested it again yet, when did u test it on anniversary update? because as I recall this bug occured when u updated the version to 0.9.17 and u added the class library package. is it resolved now is 0.9.18 version?

**Comment by touseefbsb** [comment]
@kakone  I download the repo and I tested it again with latest version **0.9.18** and I also updated **libvlcx packages** both in the sample app and also in the VLCMediaElement project. Then I connected my windows phone device with usb, because it is on **anniversary update** version and I wanted to test it on that version.

Then I ran the **sample app in debug ARM mode** on my physical device ( windows phone ) and it reaches splash screen and then an exception occurs in **MainViewModel.cs on line 124** in project **sample app**. Following is the screenshot of the exception.

![untitled](https://user-images.githubusercontent.com/11542189/32429758-e1585108-c2ed-11e7-902b-569ebe7acfa6.png)

in case you cant read the exception, following is the message of this exception.

**System.InvalidCastException: 'Unable to cast object of type 'Windows.UI.ViewManagement.ApplicationView' to type 'Windows.UI.ViewManagement.IApplicationView4'.'**

**Comment by kakone** [comment]
Yes, ViewMode doesn't exist in anniversary update. I must check it before with ApiInformation.IsApiContractPresent.

**Comment by touseefbsb** [comment]
@kakone  now the same exception occurs in VLCMediaElement project and I guess it also exists in class library project, in file mediatransportcontrols.cs at line 1038.

![untitled](https://user-images.githubusercontent.com/11542189/32442764-5f457520-c31e-11e7-8d68-d86ce4be3726.png)


Kindly test the sample app before updating. Thanks :)
