### ISSUE TITLE
RTSP stream works, but frequently stuck buffering...

### ISSUE THREAD

**Issue by DarthBergstrom** [kakone/VLC.MediaElement#38]
So I've got an RTSP stream running on a TRENDnet TV-IP314PI, I can connect to it through my windows 10 IoT UWP application (debugging through visual studio connected to a raspberry pi). 

Problem: when I stop the player, pause, or stop debugging and I try to play, unpause or start a new debug session, the stream is blank. It never says it cannot connect, it's just blank (Update: I have checked the current status of the mediaElement to see it is buffering). Randomly it will restart just fine, but more often than not it just sits there(Update: buffering). I try to pause, stop and manually restart the stream and get nothing. I've checked the web interface during failure and the stream is up (at least whichever stream the internal web application is using. Any suggestions? 

I have confirmed using software supplied with camera (to connect with RTSP stream) that the stream works just fine outside of my IoT environment. I can disconnect and reconnect without issue.

I cannot seem to find a log file on the Pi device; any advice for getting more details for troubleshooting? 

I greatly appreciate your time and assistance!!!

Update #2: I'm watching the performance on my Pi; the network activity is always good. I set my camera to a constant bitrate and even during the "buffering" issue; it's always showing about the same amount of network activity as when it is functional. The only difference between when it's stuck "buffering" and actually "playing" is the CPU usage; when stuck buffering it's at 15-18%%, when playing it's around 70%.

Update #3: Can anyone give me a list of the Options/Command-line arguments that work with this API? I've been trying some of the arguments from libvlc; but they don't seem to do anything. I've been trying to adjust the buffering/caching amount but I am not seeing hardly any I/O access from the API, and not seeing much memory change either (when using the libvlc command line arguments). 

Update #4: I setup a button to let me reset the player source (reset the connection) so that I can test various camera quality settings to see if there are any impacts to the situation (good or bad). Initially I would reset the connection 50-60 times before seeing feed again (testing multiple times). After raising the framerate I have seen a decrease in the amount of resets required before seeing my feed again. I have raised the I Frame to also see a minor decrease in resets. I noticed if I lower the framerate it gets worse, same with I frame. If I increase resolution it gets worse. Adjusting the bitrate doesn't seem to have as much affect on reconnect. Tried variable stream and constant; not much difference noted. So this leads me to believe it's a problem related to drawing the stream not receiving it - which would explain why I see the constant network activity even when stuck "buffering". It does not however explain why the status changes from Play back to buffering when getting stuck; I would assume if it were a drawing issue, the status would remain set to "playing". Once the stream is established it seems to stay on for a long time; I have not yet recorded a failure/close of stream one operational. I hate half-butt solutions, but I'm about to code this thing temporarily to detect when the status goes from playing to buffering so that it will cycle/reset the source followed by a reconnect attempt. I will report back once implemented, but I still want to figure out the real reason behind this. Thank you again for any help provided.

**Comment by DarthBergstrom** [comment]
I just noticed on debugging in VS that the vlc.mediaplayer is stuck in a "Buffering" state when it fails to come back online. If and when it does play it changes into a state of "Playing". Thoughts?

**Comment by DarthBergstrom** [comment]
For now I've got a "half-butt" solution in place. I'm checking for the status change "buffering" -> "playing" -> "buffering" and then making sure the last "buffering" status stays in place for over 1.5 seconds. Doing that over and over until it starts playing the stream. Seems to loop that way between 5-32 times before connecting and drawing the stream. Again this is only a temp solution to my issue, I still want to identify the real reason behind this.

**Comment by LeeParrishMSFT** [comment]
I've seem some instability with RTSP streams depending on the source as well. Some are stable and seem to play fine, others with seemingly the same setup can be quite troublesome. I'll share anything I find during my digging into this.

**Comment by DarthBergstrom** [comment]
Thanks Lee!

**Comment by kakone** [comment]
You can try to play your streams with the current version of  [VLC for UWP](https://www.microsoft.com/store/p/vlc/9nblggh4vvnh). If it works well, then it will work when I will update the libVLCX nuget package (very soon). If it doesn't work with VLC for UWP, you can [create an issue](https://code.videolan.org/videolan/vlc-winrt/issues) with a sample stream that doesn't work.

**Comment by DarthBergstrom** [comment]
I'm using VLC.MediaElement v0.9.17 and libVLCX v0.9.4; is that not the current version? I added them to my project via NuGet.

**Comment by DarthBergstrom** [comment]
Would either of you be able to tell me if there is a way to zoom in on my stream? I have a 720p resolution feed but would like to zoom in on a section of the video without making the element larger than the canvas. Is there a way to do this with the MediaElement? I've tried setting zoom to "true" and then stretch to "uniform to fill"; however, that only seems to affect the poster image not the stream itself. Thoughts? Again thank you guys for the assistance.

**Comment by DarthBergstrom** [comment]
update: I was able to setScale properly on the vlc.mediaPlayer.SetScale() once the mediaElement reached a status of "Playing"; However, I cannot figure out how to get vlc.mediaPlayer.SetCropGeometry() to work.  I tried the (heightxwidth+top+left) format - "480x800+10+10", but that doesn't do anything (at least when setting on change of status to "playing"). Any other ideas?

**Comment by thanhnha40** [comment]
I have the same problem stream frequently stuck buffering. i use raspberry pi.when its stuck I stop streaming and Replay sometime it work, some time it don't work. Are there any ideas to fix its. I greatly appreciate assistance

**Comment by kakone** [comment]
You can try with the [new 0.9.18 version](https://www.nuget.org/packages/VLC.MediaElement/0.9.18).

**Comment by thanhnha40** [comment]
No luck. there are exception while starting application. "Requested Windows Runtime type 'libVLCX.Instance' is not registered." I try to user nugget and project example but the same problem.

**Comment by kakone** [comment]
Strange error, I don't have this problem. Can you try with the [VLC.MediaElement.ClassLibrary nuget package](https://www.nuget.org/packages/VLC.MediaElement.ClassLibrary) instead ?

**Comment by thanhnha40** [comment]
I already check VLC.MediaElement.ClassLibrary nuget, the same problem. It work in PC but in Raspberry It not work.
