### ISSUE TITLE
Update for libVLCX?

### ISSUE THREAD

**Issue by LeeParrishMSFT** [kakone/VLC.MediaElement#39]
Since this library depends on LibVLCX is there any way to get an update to LibVLCX since it's a build from back in Feb and they've made a significant number of changes/fixes on the VideoLan project since then?

**Comment by nograx** [comment]
Would be great.

**Comment by kakone** [comment]
They've made a significant number of changes/fixes but they also introduced some annoying bugs (like this [issue](https://code.videolan.org/videolan/vlc-winrt/issues/194)).
But, anyway, I will update the libVLC package soon (I hope next week, I must do some few little changes in VLC.MediaElement corresponding to this new libVLX package).

**Comment by LeeParrishMSFT** [comment]
Thanks, if there are major problems with the current LibVLCX builds then it might make sense to either wait until they are resolved, or go back a few releases to a more stable version. I'm just finding a few things where the current UWP app seems to be more stable with some video streams than what I can do using VLC.MediaElement and was wanting to get closer parity between them. It's mainly around RTSP from devices such as Teredek that seem to be somewhat unstable.

**Comment by LeeParrishMSFT** [comment]
Sorry, hit the wrong button... Didn't mean to close it...

**Comment by LeeParrishMSFT** [comment]
(Sorry closed this by not watching and hitting the wrong button)

Thanks, if there are major problems with the current LibVLCX builds then it might make sense to either wait until they are resolved, or go back a few releases to a more stable version. I'm just finding a few things where the current UWP app seems to be more stable with some video streams than what I can do using VLC.MediaElement and was wanting to get closer parity between them. It's mainly around RTSP from devices such as Teredek that seem to be somewhat unstable.
