### ISSUE TITLE
fullscreen stucks after sometime and remains fullscreen

### ISSUE THREAD

**Issue by touseefbsb** [kakone/VLC.MediaElement#40]
aftera while, 10-15 minutes of continues video playing in fullscreen, media element never comes back to normal state and remains at fullscreen, it doesn't matter whether I try to programmatically toggle fullscreen or use the default button on the player, but player remains fullscreen.

**Comment by kakone** [comment]
I couldn't reproduce this bug. It's strange because I only call ApplicationView.GetForCurrentView().ExitFullScreenMode().

**Comment by touseefbsb** [comment]
ok I will try this as well thanks
