### ISSUE TITLE
Is there a plan to upgrade from MediaElement to MediaPlayerElement?

### ISSUE THREAD

**Issue by TaoziDB** [kakone/VLC.MediaElement#41]
As title, or a way to work with MediaPlayerElement, thanks.

**Comment by kakone** [comment]
There is no underlying System.Windows.Controls.MediaElement in the VLC.MediaElement control. I only cloned the look of the MediaElement. So, there is no way to work with MediaPlayerElement. What would be the interest ?

**Comment by TaoziDB** [comment]
Mainly because MediaPlayerElement is much easier to do background media playback, especially background audio playback on XBox.

Also, MediaPlayerElement is newer and recommended going forward.

**Comment by kakone** [comment]
As I don't use MediaElement actually, I can update the class to look like the MediaPlayerElement but it won't change anything in our case. The VLC.MediaElement control looks like to the MediaElement but the underying MediaPlayer is VLC.

**Comment by touseefbsb** [comment]
@kakone  the reason MediaPlayerElement is better than MediaElement are several. some of major advantages are following.
1. we wont need to write any code for system media transport controls as that is built in with MediaPlayerElement.
2. MediaPlayerElement can be subject to any XAML surface which opens multiple new scenarios to create apps.
3. MPE can have multiple instances running at the same time.

are you saying you are only using style and not the functionality of the MediaElement? if that is the case then you are probably right in this case upgrading to MediaPlayerElement wont be much beneficial.

**Comment by kakone** [comment]
Yes, I'm using only the style of the MediaElement. All the rendering stuff is done by VLC.

**Comment by touseefbsb** [comment]
oh alright then
