### ISSUE TITLE
The arm version cannot pass the test

### ISSUE THREAD

**Issue by ZhaoYunxiong** [kakone/VLC.MediaElement#43]
I compiled the release version of arm, and then started Windows App Cert Kit to test it, and the test results failed.
The test report points out that the  API "if_nametoindex" in iphlpapi.dll is not supported by the platform,
libvlccore.dll calls this API.
So I can't submit my application to the windows store.
How to solve it?

**Comment by touseefbsb** [comment]
@ZhaoYunxiong  have you found out reason of test failed yet? and also which version of libvlcx are you using? is it the latest?

**Comment by ZhaoYunxiong** [comment]
@touseefbsb After I compiled the arm release with visual studio, it automatically popped the window to start the "Windows App Cert Kit" to test the application, and the test results failed. The test report points out that the API "if_nametoindex" in iphlpapi.dll is not supported by the platform, libvlccore.dll calls this API. 
I compiled the application can run on the phone, but can not submit to the store.
The libvlc version I used was 0.9.6.
You can try to compile the arm release of [SampleApp](https://github.com/kakone/VLC.MediaElement/tree/master/SampleApp)
When you compile successfully, visual studio pops up the window to test this application, The test results should be failed.

**Comment by touseefbsb** [comment]
@ZhaoYunxiong  Please let us know as well if you are able to find solution to this issue :)

**Comment by kakone** [comment]
Annoying bug... I think we can't do anything in our side. I will try to ask to the VLC team.

**Comment by touseefbsb** [comment]
yeah we cnt do anything this has to be done by vlc team within the package libvlcx

**Comment by ZhaoYunxiong** [comment]
Others also discovered this problem.
[Windows phone 10 - libvlccore.dll - if_nametoindex](https://forum.videolan.org/viewtopic.php?f=37&t=141087)

**Comment by mfkl** [comment]
Hey guys,
Sorry for the delay, here's a working build https://drive.google.com/open?id=1Gxd0u_3XuIpsrNhkXXsRI6BptwqoYquF.
Note that I noticed some regressions regarding playback on some AVI files via SMB.

**Comment by kakone** [comment]
Thanks Martin, I will update the [libVLCX package](https://www.nuget.org/packages/libVLCX).

**Comment by ZhaoYunxiong** [comment]
@kakone  Have you made any progress?

**Comment by kakone** [comment]
You can try [VLC.MediaElement 0.9.20](https://www.nuget.org/packages/VLC.MediaElement).

**Comment by ZhaoYunxiong** [comment]
That's okay
