### ISSUE TITLE
Crash on ARM build - Win IoT Raspberry Pi 3

### ISSUE THREAD

**Issue by abpostelnicu** [kakone/VLC.MediaElement#44]
I'm having a basic project where i only try to open a stream from a "Page". The code that i use in the XMAL is:

```
<vlc:MediaElement AreTransportControlsEnabled="False" HardwareAcceleration="True" Height="300" Width="300" Name="vlcPlayer1" Margin="691,63,33,277" BorderThickness="2" Source="Some Source">
</vlc:MediaElement>
```

The problem is that it crashes every time in:

```
#if DEBUG && !DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION
            UnhandledException += (sender, e) =>
            {
                if (global::System.Diagnostics.Debugger.IsAttached) global::System.Diagnostics.Debugger.Break();
            };
#endif 
```

The exception that is thrown is:

> Message	"Requested Windows Runtime type 'libVLCX.Instance' is not registered."

The version of the lib that I'm using is: 0.9.18
Win IoT: v.10.0.16299.19

**Comment by abpostelnicu** [comment]
I've installed libVLCX for ARM ins issue is fixed.

**Comment by kakone** [comment]
"ins" ?!? 
Issue is fixed or not with the latest version of libVLCX ?

**Comment by abpostelnicu** [comment]
yes it can be closed, thanks!
