### ISSUE TITLE
Authentication for RTSP is broken

### ISSUE THREAD

**Issue by abpostelnicu** [kakone/VLC.MediaElement#45]
Hello,

I'm trying to use the component in order to play an rtsp strea that requires authentication. The problem is I get this error wen debuting the app:

[gist link](https://gist.github.com/abpostelnicu/439a374b9bffb3122520a7f6e47f0efb)

I put the output in a pastebin 
I'm using the latest version of the library and my target platform is x64. Any hint on this matter is well appreciated.

**Comment by kakone** [comment]
Did you try by enabling privateNetworkClientServer capability ?

**Comment by abpostelnicu** [comment]
On x64 builds this still doesn't work, but on ARM it works.

**Comment by kakone** [comment]
There is a warning in your log : _Password in a URI is DEPRECATED_
Perhaps, you should try to use the ShowLoginDialog event (this event should be called if credentials are needed). You can subscribe to this event, and set the username and password in the DialogResult property of the event args :  
`e.DialogResult = new LoginDialogResult() { Username = username, Password = password };`
