### ISSUE TITLE
rtp multicast and frozen each certain time

### ISSUE THREAD

**Issue by cansado2930** [kakone/VLC.MediaElement#48]
Hello,
I’m playing with rtp over multicast and sound works correctly but video is frozen each 2 seconds, 4 seconds,… It is very frequently and I have tried with vlc desktop at the same time and same computer and I don’t have this problem. May it be a buffer problem? If it is yes, How should I increase the buffer size?
Thank you

**Comment by kakone** [comment]
Did you try with VLC desktop 3.0 or 2.2 ?

**Comment by cansado2930** [comment]
It is the 2.2.4

**Comment by mfkl** [comment]
As kakone pointed out, you should probably try with a 3.0 build and report back here whether that solves it.

x64 https://nightlies.videolan.org/build/winrt-x86_64/
x86 https://nightlies.videolan.org/build/winrt-i686/
