### ISSUE TITLE
"Could not create swapChain" in Xamarin Forms UWP project

### ISSUE THREAD

**Issue by lisardggY** [kakone/VLC.MediaElement#49]
I'm trying to initialize a MediaElement in a Xamarin Forms app, as a custom renderer for a custom control on UWP. I create the instance and set a source, but when it comes down to rendering, I get the following unhandled COMException:

> The application made a call that is invalid. Either the parameters of the call or the state of some object was incorrect.
> Enable the D3D debug layer in order to see details via debug messages.
> 
> Could not create swapChain

>    at libVLCX.Instance..ctor(IList`1 argv, SwapChainPanel panel)
>    at VLC.MediaElement.<Init>d__178.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at VLC.MediaElement.<>c__DisplayClass166_0.<<OnApplyTemplate>b__3>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
>    at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()

* I've both with the latest 0.9.20 and previous 0.9.19, with matching libVLCX versions (0.9.7, 0.9.6, respectively).
* I've tried creating the MediaElement directly in the CustomRenderer code, but also creating it in a Grid or directly in a SwapChainPanel. Same results.
* If I clone the SampleApp and run it, it *does* work fine. 
* The Xamarin Forms control it's hosted in is a regular ContentView. Is there a special D3D-aware View I should be rendering it in? Maybe a Skia SKGLView?

Has it been tested as a Xamarin Forms app?

**Comment by lisardggY** [comment]
Additional data:
* Running on Windows 10 Fall Creator Update (10.0.16299.125)
* Running in Visual Studio 2017 15.5.
* The _Internet (Client)_ capability is set, but no others - just like the sample app.

**Comment by kakone** [comment]
I didn't test it in Xamarin Forms yet (and I don't know how Xamarin Forms rendering works). The VLC media element control uses a SwapChainPanel for D3D11 rendering. Perhaps it is not compatible with Xamarin Forms, I will try to look at it quickly.

**Comment by lisardggY** [comment]
The Xamarin.Forms controls are basically placeholders, and the CustomRenderers are per-platform code that is generated in the actual app - so regardless of Xamarin, this is still simply a UWP app, but perhaps structured a bit differently. 

Additionally, I've tried compiling the control from sources and referencing it directly (rather than from NuGet) and I'm getting more specific errors now . Specifically, it seems there's a FileNotFoundException thrown here:

>    at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
>    at libVLCX.Instance..ctor(IList`1 argv, SwapChainPanel panel)
>    at VLC.MediaElement.<InitAsync>d__178.MoveNext() in c:\projects\VLC.MediaElement\VLCMediaElement\MediaElement.cs:line 465
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at VLC.MediaElement.<>c__DisplayClass166_0.<<OnApplyTemplate>b__3>d.MoveNext() in c:\projects\VLC.MediaElement\VLCMediaElement\MediaElement.cs:line 371
> 

Since the only thing in the InitAsync that seems to care about files is the `--keystore-file` parameter, I'll try to see if the result of ApplicationData.Current.LocalFolder.Path and KeyStoreFilename are null for some reason.

**Comment by lisardggY** [comment]
And indeed, the file `VLC_MediaElement_KeyStore` doesn't exist under the LocalFolder.Path. Is it supposed to be generated by something?

**Comment by lisardggY** [comment]
Ok, that appears to have been a false lead. I had a broken reference to the C++ Runtime components. Now that I fixed it, I get the same "could not created swapChain" error again.

**Comment by kakone** [comment]
`keystore` is the a path where keys (like username, password, ...) will be stored if needed. It will not be used in your case.
As you guessed, you need the `Microsoft Visual C++ 2013 Runtime Package for Windows Universal`. It is automatically added by the [NuGet package](https://github.com/kakone/VLC.MediaElement/blob/master/VLCMediaElement/VLC.MediaElement.targets).

**Comment by kakone** [comment]
OK, I understood the problem. In Xamarin Forms, the ViewRenderer has no size when is added to the visual tree. But the SwapChainPanel must have a width and height when InitAsync is called.
If I deffer the call of InitAsync method in UpdateSizeAsync, it works great.

**Comment by lisardggY** [comment]
Ah, wonderful. Once you push the changes, I'll pull and see if it fixes it on my end as well.

**Comment by kakone** [comment]
The [version 0.9.21](https://www.nuget.org/packages/VLC.MediaElement) should fix the problem.

**Comment by lisardggY** [comment]
And we have video! Fantastic. Thanks for the quick fix!

**Comment by JunielKatarn** [comment]
Hi, @lisardggY. I'm also trying to use VLC.MediaElement in a Xamarin.Forms UWP app, but the mediaElement.MediaPlayer property stays null (likely, it never gets initialized).

Do you have any pointers on how to set up the MediaElement correctly?
