### ISSUE TITLE
Exception when creating second VLC.MediaElement 

### ISSUE THREAD

**Issue by panzur** [kakone/VLC.MediaElement#5]
If I have a page that has vlc:MediaElement like this
`<Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <vlc:MediaElement AreTransportControlsEnabled="True" HardwareAcceleration="True">
            <vlc:MediaElement.TransportControls>
                <vlc:MediaTransportControls ControlPanelOpacity="0.8"  />
            </vlc:MediaElement.TransportControls>
        </vlc:MediaElement>
    </Grid>`

After I leave page and try to access page again (page ui is recreated) the app crashes on MediaElement.cs line 287 `swapChainPanel.Loaded += async (sender, e) => await Init(swapChainPanel);`

So how to create second VLC.MediaElement  without crashing?

**Comment by kakone** [comment]
Fixed in [version 0.9.8](https://www.nuget.org/packages/VLC.MediaElement)
