### ISSUE TITLE
FullScreen not working...

### ISSUE THREAD

**Issue by SARAVANAN94434** [kakone/VLC.MediaElement#51]
How to play in FullScreen mode.....when i click full screen icon application goes to fullscreen mode not the player....Player remains in the same size..

And i want  using this vlc:MediaElement in NavigationView App (Fall Creators Update)..Tell me how to view in fullscreen mode...Normal MediaElement,MediaPlayerElement Working good in same App ..

**Comment by kakone** [comment]
I don't know how I can manage a real fullscreen mode from the control itself. If someone has an idea...
So, you must do it yourself. You must subscribe to the `Window.Current.CoreWindow.SizeChanged` event. If `Windows.UI.ViewManagement.ApplicationView.GetForCurrentView().IsFullScreen`, you must hide your controls to show only the VLC.MediaElement control at the size of the window.

**Comment by SARAVANAN94434** [comment]
i did Double Tapped Event.... and i set width and Height of the Player to Maximum.....it goes entered size ..

But it did't hide Navigation view....

Tell me how to hide Navigation View or hamburger menu..

**Comment by kakone** [comment]
I don't know.
What you can do is to have your navigation view over the VLC.MediaElement. And you hide your NavigationView in fullscreen mode (but I don't know if this may be appropriate in your application).

**Comment by kakone** [comment]
In my own app ([screenshot](https://user-images.githubusercontent.com/1640329/35154265-df19682a-fd29-11e7-9ecd-1536c0af755b.png)), I have a ListView in the Content property of VLC.MediaElement. This menu auto hides like the controls of the mediaElement.

**Comment by SARAVANAN94434** [comment]
List View or Grid View are should auto hide....But im using Navigation View in my app....i dont Know how to hide it....

if you know how to hide Navigation view or hamburger menu when full screen mode..

And what kinde of Application is yours...Is it regarding Live channels..

**Comment by SARAVANAN94434** [comment]
Please Tell me if you Know..

**Comment by touseefbsb** [comment]
@SARAVANAN94434  I can suggest u a scenario, put your navigation view in a frame and then navigate that frame to page with only the vlc media element, this way when u go to page to play media there will be no navigation view there. let me know if you need more explanation on this :)

**Comment by SARAVANAN94434** [comment]
@touseefbsb  yes .. please give me some samples

**Comment by touseefbsb** [comment]
@SARAVANAN94434  Its not that complicated. the main Frame contains the mainpage with has the navigation view. and navigation view has a frame which switches between all other pages. so when u click a file to play then u can navigate ur main frame from Mainpage -> Media Element page. do u have any knowledge of frames or have u heard it for the first time?

**Comment by SARAVANAN94434** [comment]
@touseefbsb .. I only know little bit... can you give me some sample..

**Comment by touseefbsb** [comment]
@SARAVANAN94434  here is a sample https://github.com/touseefbsb/navigationwithmedia

**Comment by SARAVANAN94434** [comment]
@touseefbsb  Thanks for the sample Bro.. But Your contains no Frame.....

Please see my sample app and fix....

Here my sample [https://github.com/SARAVANAN94434/Navigation-View](url)

**Comment by touseefbsb** [comment]
@SARAVANAN94434  I didnt define a frame explicitly, but there is a top level frame in every uwp app and I switched the pages in that app. you have to read more on the microsoft docs about frames in order to understand the concept. see the c# code behind in mainpage.xaml.cs and mediapage.xaml.cs in order to see whats happening :)

**Comment by touseefbsb** [comment]
btw I cant open your repo it says page not found

**Comment by SARAVANAN94434** [comment]
But for me it working.... you just click  Rebuild Solution....if not working please see my code .....

**Comment by touseefbsb** [comment]
that is wht I am saying I cannot see ur code that link is not working

**Comment by touseefbsb** [comment]
my sample doesnt contain a frame, forget the frame and just follow the concept I am giving u in my sample app and you can replicate that in your app :)

**Comment by SARAVANAN94434** [comment]
Sorry Bro.... the Link Not Working....  Plaese see this Link

[https://github.com/SARAVANAN94434/MediaElement](url)
or
[http://www.mediafire.com/file/ynyauwfw83wc4ir/App1.zip](url)

**Comment by touseefbsb** [comment]
Ive seen your code, your mainpage is like my mainpage with navigation view, I made mediapage and you have vlc.xaml page so just look at my code and you will know how to solve it, there is nothing special going on here, i provided you the simplest code possible. I used a button to click and go to the media page, Now you have to decide when do you want to go to the media page and in that event use the Frame.Navigate() method, see my sample code in mainpage.xaml.cs and mediapage.xaml.cs
