### ISSUE TITLE
How to change Audio track....

### ISSUE THREAD

**Issue by SARAVANAN94434** [kakone/VLC.MediaElement#54]
my streaming link has dual audio track...so its playing both audios like left side speaker has one audio track and right side speaker has another audio track....

how to select audio tracks.....and how to view available audio tracks..

**Comment by kakone** [comment]
If there are multiple audio tracks, this icon 
![image](https://user-images.githubusercontent.com/1640329/35362934-ca85d1c2-0167-11e8-883b-79f20edf7c6f.png)
 should appear in the controls.
