### ISSUE TITLE
Problem with webm by url. Windows Phone 10

### ISSUE THREAD

**Issue by ta-tikoma** [kakone/VLC.MediaElement#56]
I create project with VLC.MediaElement and add this code:
`mediaElement.Source = "https://drive.google.com/uc?export=download&confirm=no_antivirus&id=1a5a-n9udlPgfeqVr8kSuUZvcFqBkQyr9";`

But then I run app player said: 
`Your input can t be opened vlc is unable to open the mrl Check the log for more details.`

Then I add Logging:
`mediaElement.Logging += Logging;`
`...`
 `private void Logging(object sender, VLC.LogRoutedEventArgs e)`
` {`
`     System.Diagnostics.Debug.WriteLine("Log:" + e.Message);`
` }`

and after I run, app crash with message:
`Log:[main] (\vlc-winrt-compile\vlc-msvc\vlc\src\input\input.c:301) Creating an input for 'uc?export=download&confirm=no_antivirus&id=1a5a-n9udlPgfeqVr8kSuUZvcFqBkQyr9'`
`Exception thrown: 'System.Exception' in VLC.winmd`
`Программа "[7716] nn2ch.sln.exe" завершилась с кодом -1073741819 (0xc0000005) 'Access violation'.`

I try any links with webm files but have previous result.

But if I download file and set him to player via `StorageApplicationPermissions.FutureAccessList` all work good. But after close file - memory not clear (I use `StorageApplicationPermissions.FutureAccessList.Clear();`) and I after play many files app crach becose memory is full.

Can you help me?

**Comment by kakone** [comment]
Can you try your link in [VLC for UWP](https://www.microsoft.com/store/p/vlc/9nblggh4vvnh) ? Does it work ?

**Comment by ta-tikoma** [comment]
I try, it doesn't work.

**Comment by kakone** [comment]
It should work now with the [version 3.0.1](https://www.nuget.org/packages/VLC.MediaElement/3.0.1).

**Comment by ta-tikoma** [comment]
I try new version 3.0.1, but see same result.

**Comment by ta-tikoma** [comment]
New version 3.1.0.1 and now it's work: webm play via link. So many thanks @kakone !
