### ISSUE TITLE
Connect to RTSP security camera

### ISSUE THREAD

**Issue by lisardggY** [kakone/VLC.MediaElement#58]
I'm trying to display a feed that's piped directly from a video camera (or maybe from an on-site video server, I'm not sure at this point), which I have as an authenticated RTSP feed (i.e. rtsp://user:pass@10.0.0.0/feed). But the VLC.MediaElement, which shows normal HTTP feeds fine, won't show anything, and keep raising "MediaEnded" events. 

Following tips in other closed issues, I tried opening the feed in the UWP VLC App (it opens fine in the classic VLC app), and sure enough, it fails there as well. VLC's log files, and found this: "only real/helix rtsp servers supported for now", which seems to indicate that the libvlcx used in UWP doesn't support this specific flavor of RTSP.

Is there any way to bypass this issue? Either in the libvlcx, in the MediaElement control, or using some other library (free or paid)?

**Comment by kakone** [comment]
cf #62 discussion
