### ISSUE TITLE
iP Cameras

### ISSUE THREAD

**Issue by cahernanz** [kakone/VLC.MediaElement#6]
Can be used passing an ipCamera uri?

**Comment by kakone** [comment]
Yes, it should work (add privateNetworkClientServer capability to your app). If you need to authenticate, you can use the ShowLoginDialog event (set the Username and Password in the event args).

**Comment by cahernanz** [comment]
Thanks for your reply, the idea is having an ACTi acm-1011 ip camera waiting in preview until I start one function to record video using vlc. I think it is possible using libvlcx and MediaElement.

**Comment by cahernanz** [comment]
So, i have next problem. I need authentication automatically and the "source" of vlc.MediaElement can´t decode this url. If I pass the url without credentials, i get this error in the main page.

![imagen](https://cloud.githubusercontent.com/assets/20541186/23071087/86e30436-f52d-11e6-92e3-0fbfed4e268b.png)

this is the url: Source="http://192.168.0.21:6021/cgi-bin/cmd/encoder?GET_STREAM"

**Comment by kakone** [comment]
What do you mean by "I need authentication automatically" ?

**Comment by cahernanz** [comment]
Sorry, i mean, i need to pass the url with user and password, not open a login dialog window to insert it.
I had problems passing urls like http://user:pass@ip:port/command. it crashes. Because as I said in desktop version of vlc i dont have problems to pass the url, you know viewing screen captures i uploaded.

Thanks a  lot in advance

**Comment by kakone** [comment]
With the ShowLoginDialog event, you can set the username and password without showing a dialog box. I will add the support of the credentials in the url but actually, you can use the ShowLoginDialog, it should work.

**Comment by casiopeus** [comment]
Hello!. I am having similar problems with ip cameras. I tried on ACTi and Axis .I need to pass credential parameters in URL, but if I pass the url with parameters, program stops. 

I don´t understand how show dialog event works, and how to set credential parameters are set inside. Anyone of you would give me a simple example of how this event handler work?, and how to pass the command to vlc to start/play the recording?

TYSM!

**Comment by kakone** [comment]
Normally, the ShowLoginDialog event is called if credentials are needed. So, if you subscribe to this event, you can just set the username and password in the event args.
If you want to show an async login dialog to your user to ask the username and the password, use this code :
```
using (var deferral = e.GetDeferral())
{
    await ... // show your login dialog box with an async operation
    e.Username = username;
    e.Password = password;
}
```

I didn't tested it but I think you can also set the username and password with the Options property (add these lines of code before setting the Source) :
```
vlcMediaElement.Options.Add("sout-http-user", user);
vlcMediaElement.Options.Add("sout-http-pwd", password);
```

**Comment by kakone** [comment]
Fixed in [version 0.9.10](https://www.nuget.org/packages/VLC.MediaElement/0.9.10), you can now use http://user:pass@xyz directly.

**Comment by casiopeus** [comment]
This is much better!. Thanks a lot!

**Comment by cahernanz** [comment]
Thank you so much kakone. I tried using ShowDialogEvent but this is perfect. It works perfectly whit my ACTi ip cam. just pass in the source the url with credentials.

I reccomend.
