### ISSUE TITLE
Certification error with latest version (3.0.1.2)

### ISSUE THREAD

**Issue by nograx** [kakone/VLC.MediaElement#64]
Hi,

I'm getting an error on certification with the latest VLC.MediaElement (3.0.1.2), but only on the **x86** component (ARM and x64 seems OK):

# Windows security features test

## FAILED
Binary analyzer
Error Found: The binary analyzer test detected the following errors:
File libvlc.dll has failed the SafeSEHCheck check.
File libvlccore.dll has failed the SafeSEHCheck check.
File plugins\access\libaccess_concat_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libaccess_imem_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libaccess_mms_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libaccess_realrtsp_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libattachment_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libdsm_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libfilesystem_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libftp_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libhttps_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libhttp_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libidummy_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libimem_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\liblive555_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libnfs_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\librtp_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libsatip_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libsdp_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libsftp_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libshm_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libtcp_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libtimecode_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libudp_plugin.dll has failed the SafeSEHCheck check.
File plugins\access\libvdr_plugin.dll has failed the SafeSEHCheck check.
File plugins\access_output\libaccess_output_dummy_plugin.dll has failed the SafeSEHCheck check.
File plugins\access_output\libaccess_output_file_plugin.dll has failed the SafeSEHCheck check.
File plugins\access_output\libaccess_output_http_plugin.dll has failed the SafeSEHCheck check.
File plugins\access_output\libaccess_output_livehttp_plugin.dll has failed the SafeSEHCheck check.
File plugins\access_output\libaccess_output_shout_plugin.dll has failed the SafeSEHCheck check.
File plugins\access_output\libaccess_output_udp_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libaudiobargraph_a_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libaudio_format_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libchorus_flanger_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libcompressor_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libdolby_surround_decoder_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libequalizer_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libgain_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libheadphone_channel_mixer_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libkaraoke_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libmad_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libmono_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libnormvol_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libparam_eq_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libremap_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libsamplerate_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libscaletempo_pitch_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libscaletempo_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libsimple_channel_mixer_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libspatialaudio_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libspatializer_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libspeex_resampler_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libstereo_widen_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libtospdif_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libtrivial_channel_mixer_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_filter\libugly_resampler_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_mixer\libfloat_mixer_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_mixer\libinteger_mixer_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_output\libadummy_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_output\libafile_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_output\libamem_plugin.dll has failed the SafeSEHCheck check.
File plugins\audio_output\libwasapi_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libadpcm_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libaes3_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libaraw_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libavcodec_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libcc_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libcdg_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libcvdsub_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libd3d11va_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libdca_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libddummy_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libdvbsub_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libedummy_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libflac_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libfluidsynth_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libg711_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libjpeg_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libkate_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\liblibass_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\liblibmpeg2_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\liblpcm_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libmft_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libmpg123_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\liboggspots_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libopus_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libpng_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\librawvideo_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\librtpvideo_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libscte18_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libscte27_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libspdif_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libspeex_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libspudec_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libstl_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libsubsdec_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libsubstx3g_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libsubsusf_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libsvcdsub_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libt140_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libtextst_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libtheora_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libttml_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libuleaddvaudio_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libvorbis_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libvpx_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libwebvtt_plugin.dll has failed the SafeSEHCheck check.
File plugins\codec\libzvbi_plugin.dll has failed the SafeSEHCheck check.
File plugins\control\libdummy_plugin.dll has failed the SafeSEHCheck check.
File plugins\control\libgestures_plugin.dll has failed the SafeSEHCheck check.
File plugins\control\libhotkeys_plugin.dll has failed the SafeSEHCheck check.
File plugins\control\libnetsync_plugin.dll has failed the SafeSEHCheck check.
File plugins\d3d11\libdirect3d11_filters_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libadaptive_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libaiff_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libasf_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libau_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libavi_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libcaf_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libdemuxdump_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libdemux_cdg_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libdemux_chromecast_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libdemux_stl_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libdiracsys_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libdirectory_demux_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libes_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libflacsys_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libgme_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libh26x_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libimage_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libmjpeg_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libmkv_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libmp4_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libmpc_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libmpgv_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libnoseek_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libnsc_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libnsv_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libnuv_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libogg_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libplaylist_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libps_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libpva_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\librawaud_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\librawdv_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\librawvid_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libreal_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libsid_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libsmf_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libsubtitle_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libts_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libtta_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libty_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libvc1_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libvobsub_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libvoc_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libwav_plugin.dll has failed the SafeSEHCheck check.
File plugins\demux\libxa_plugin.dll has failed the SafeSEHCheck check.
File plugins\keystore\libfile_keystore_plugin.dll has failed the SafeSEHCheck check.
File plugins\keystore\libmemory_keystore_plugin.dll has failed the SafeSEHCheck check.
File plugins\logger\libconsole_logger_plugin.dll has failed the SafeSEHCheck check.
File plugins\logger\libfile_logger_plugin.dll has failed the SafeSEHCheck check.
File plugins\lua\liblua_plugin.dll has failed the SafeSEHCheck check.
File plugins\meta_engine\libfolder_plugin.dll has failed the SafeSEHCheck check.
File plugins\meta_engine\libtaglib_plugin.dll has failed the SafeSEHCheck check.
File plugins\misc\libaddonsfsstorage_plugin.dll has failed the SafeSEHCheck check.
File plugins\misc\libaddonsvorepository_plugin.dll has failed the SafeSEHCheck check.
File plugins\misc\libaudioscrobbler_plugin.dll has failed the SafeSEHCheck check.
File plugins\misc\libexport_plugin.dll has failed the SafeSEHCheck check.
File plugins\misc\libfingerprinter_plugin.dll has failed the SafeSEHCheck check.
File plugins\misc\libgnutls_plugin.dll has failed the SafeSEHCheck check.
File plugins\misc\liblogger_plugin.dll has failed the SafeSEHCheck check.
File plugins\misc\libstats_plugin.dll has failed the SafeSEHCheck check.
File plugins\misc\libvod_rtsp_plugin.dll has failed the SafeSEHCheck check.
File plugins\misc\libxml_plugin.dll has failed the SafeSEHCheck check.
File plugins\mux\libmux_asf_plugin.dll has failed the SafeSEHCheck check.
File plugins\mux\libmux_avi_plugin.dll has failed the SafeSEHCheck check.
File plugins\mux\libmux_dummy_plugin.dll has failed the SafeSEHCheck check.
File plugins\mux\libmux_mp4_plugin.dll has failed the SafeSEHCheck check.
File plugins\mux\libmux_mpjpeg_plugin.dll has failed the SafeSEHCheck check.
File plugins\mux\libmux_ogg_plugin.dll has failed the SafeSEHCheck check.
File plugins\mux\libmux_ps_plugin.dll has failed the SafeSEHCheck check.
File plugins\mux\libmux_ts_plugin.dll has failed the SafeSEHCheck check.
File plugins\mux\libmux_wav_plugin.dll has failed the SafeSEHCheck check.
File plugins\packetizer\libpacketizer_a52_plugin.dll has failed the SafeSEHCheck check.
File plugins\packetizer\libpacketizer_copy_plugin.dll has failed the SafeSEHCheck check.
File plugins\packetizer\libpacketizer_dirac_plugin.dll has failed the SafeSEHCheck check.
File plugins\packetizer\libpacketizer_dts_plugin.dll has failed the SafeSEHCheck check.
File plugins\packetizer\libpacketizer_flac_plugin.dll has failed the SafeSEHCheck check.
File plugins\packetizer\libpacketizer_h264_plugin.dll has failed the SafeSEHCheck check.
File plugins\packetizer\libpacketizer_hevc_plugin.dll has failed the SafeSEHCheck check.
File plugins\packetizer\libpacketizer_mlp_plugin.dll has failed the SafeSEHCheck check.
File plugins\packetizer\libpacketizer_mpeg4audio_plugin.dll has failed the SafeSEHCheck check.
File plugins\packetizer\libpacketizer_mpeg4video_plugin.dll has failed the SafeSEHCheck check.
File plugins\packetizer\libpacketizer_mpegaudio_plugin.dll has failed the SafeSEHCheck check.
File plugins\packetizer\libpacketizer_mpegvideo_plugin.dll has failed the SafeSEHCheck check.
File plugins\packetizer\libpacketizer_vc1_plugin.dll has failed the SafeSEHCheck check.
File plugins\services_discovery\libmediadirs_plugin.dll has failed the SafeSEHCheck check.
File plugins\services_discovery\libmicrodns_plugin.dll has failed the SafeSEHCheck check.
File plugins\services_discovery\libpodcast_plugin.dll has failed the SafeSEHCheck check.
File plugins\services_discovery\libsap_plugin.dll has failed the SafeSEHCheck check.
File plugins\services_discovery\libupnp_plugin.dll has failed the SafeSEHCheck check.
File plugins\spu\libaudiobargraph_v_plugin.dll has failed the SafeSEHCheck check.
File plugins\spu\liblogo_plugin.dll has failed the SafeSEHCheck check.
File plugins\spu\libmarq_plugin.dll has failed the SafeSEHCheck check.
File plugins\spu\libmosaic_plugin.dll has failed the SafeSEHCheck check.
File plugins\spu\libremoteosd_plugin.dll has failed the SafeSEHCheck check.
File plugins\spu\librss_plugin.dll has failed the SafeSEHCheck check.
File plugins\spu\libsubsdelay_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_extractor\libarchive_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_filter\libadf_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_filter\libcache_block_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_filter\libcache_read_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_filter\libhds_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_filter\libinflate_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_filter\librecord_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_filter\libskiptags_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_out\libstream_out_autodel_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_out\libstream_out_bridge_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_out\libstream_out_chromecast_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_out\libstream_out_cycle_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_out\libstream_out_delay_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_out\libstream_out_description_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_out\libstream_out_display_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_out\libstream_out_dummy_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_out\libstream_out_duplicate_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_out\libstream_out_es_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_out\libstream_out_gather_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_out\libstream_out_mosaic_bridge_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_out\libstream_out_record_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_out\libstream_out_rtp_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_out\libstream_out_setid_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_out\libstream_out_smem_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_out\libstream_out_standard_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_out\libstream_out_stats_plugin.dll has failed the SafeSEHCheck check.
File plugins\stream_out\libstream_out_transcode_plugin.dll has failed the SafeSEHCheck check.
File plugins\text_renderer\libfreetype_plugin.dll has failed the SafeSEHCheck check.
File plugins\text_renderer\libtdummy_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_chroma\libchain_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_chroma\libgrey_yuv_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_chroma\libi420_10_p010_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_chroma\libi420_nv12_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_chroma\libi420_rgb_mmx_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_chroma\libi420_rgb_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_chroma\libi420_rgb_sse2_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_chroma\libi420_yuy2_mmx_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_chroma\libi420_yuy2_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_chroma\libi420_yuy2_sse2_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_chroma\libi422_i420_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_chroma\libi422_yuy2_mmx_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_chroma\libi422_yuy2_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_chroma\libi422_yuy2_sse2_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_chroma\librv32_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_chroma\libswscale_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_chroma\libyuvp_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_chroma\libyuy2_i420_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_chroma\libyuy2_i422_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libadjust_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libalphamask_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libanaglyph_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libantiflicker_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libball_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libblendbench_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libblend_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libbluescreen_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libcanvas_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libcolorthres_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libcroppadd_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libdeinterlace_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libedgedetection_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\liberase_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libextract_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libfps_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libfreeze_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libgaussianblur_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libgradfun_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libgradient_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libgrain_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libhqdn3d_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libinvert_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libmagnify_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libmirror_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libmotionblur_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libmotiondetect_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\liboldmovie_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libposterize_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libpostproc_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libpsychedelic_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libpuzzle_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libripple_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\librotate_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libscale_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libscene_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libsepia_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libsharpen_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libtransform_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libvhs_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_filter\libwave_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_output\libdirect3d11_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_output\libdrawable_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_output\libflaschen_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_output\libvdummy_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_output\libvmem_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_output\libyuv_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_splitter\libclone_plugin.dll has failed the SafeSEHCheck check.
File plugins\video_splitter\libwall_plugin.dll has failed the SafeSEHCheck check.
File plugins\visualization\libvisual_plugin.dll has failed the SafeSEHCheck check.

Kind regards,
Peter

**Comment by vbfnet** [comment]
Hello,

I am also getting the same error. 

The resolution in MSDN says "Enable the /SAFESEH option in the linker command when you build your app. This option is on by default in the Release configurations of Visual Studio. Verify this option is enabled in the build instructions for all executable modules in your app."

Any idea how to do this for C# app in Visual studio?

Best Regards

**Comment by nograx** [comment]
I think you have to do this on the VLC library it's elf, so nothing we can do by ourself.

**Comment by vbfnet** [comment]
Thanks for the update.

So there is no choice left for publishing this on Windows Store for x86. 

But for x64 and ARM, this should not be a problem.

**Comment by kakone** [comment]
I'm going to generate a new version of [libVLCX](https://www.nuget.org/packages/libVLCX/) as soon as possible to correct this problem.

**Comment by vbfnet** [comment]
Thank you, that would be really great. 


Also , if you have time to look into the below problems, that would be great. 
 1. The MediaOpened,.MediaEnded, MediaFailed  events crash with threading issues. I see a merge request to fix this problem.
2. The volume button and the aspect ratio button does not respond to inputs. There are no events available to handle this in code-behind.

Best regards.

**Comment by kakone** [comment]
> There are no events available to handle this in code-behind.

I don't understand, there are 2 dependency properties for the volume and aspect ratio. So, you can use the [RegisterPropertyChangedCallback](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.dependencyobject.registerpropertychangedcallback) method.

**Comment by vbfnet** [comment]
Thanks, I will try that.

Best regards.

**Comment by kakone** [comment]
Could you test the certification with the new [NuGet package 3.1.0](https://www.nuget.org/packages/VLC.MediaElement/3.1.0) ?

**Comment by vbfnet** [comment]
I ran the Certification test and now the  SafeSEHCheck check error no longer appears.

But now there is new error. See below

Supported API test

FAILED
Supported APIs

Error Found: The supported APIs test detected the following errors:
API DisposeMediaSession in intel_gfx_api-x86.dll is not supported for this application type. libqsv_plugin.dll calls this API.
API InitialiseMediaSession in intel_gfx_api-x86.dll is not supported for this application type. libqsv_plugin.dll calls this API.

**Comment by kakone** [comment]
Indeed, I was able to reproduce the problem with the certification kit : 
``API DisposeMediaSession in intel_gfx_api-x86.dll is not supported for this application type. libqsv_plugin.dll calls this API.``

@mfkl Did you encountered this error when certifing ? Any workaround ?

**Comment by mfkl** [comment]
Yes, forgot to let you know about this. 

We have special authorization from MSFT on our app, I'm afraid you should probably comment out the reference.

**Comment by kakone** [comment]
I will do a new version ASAP of the [libVLCX](https://www.nuget.org/packages/libVLCX/) package, commenting out the reference, this should work around the problem.

**Comment by kakone** [comment]
Corrected in version [3.1.0.1](https://www.nuget.org/packages/VLC.MediaElement/3.1.0.1)

**Comment by vbfnet** [comment]
With version 3.1.0.1, the X64, x86 and ARM version passed certification in Windows Store and  my app is now live in Windows Store.

Thank you @kakone for creating the VLC package !!!
