### ISSUE TITLE
Any given file path crashes

### ISSUE THREAD

**Issue by Noemata** [kakone/VLC.MediaElement#7]
Not sure what the correct approach would be.  I expected this to work (crashes):

        private async void OnClick(object sender, Windows.UI.Xaml.RoutedEventArgs e)
        {
            // Create and open the file picker
            FileOpenPicker openPicker = new FileOpenPicker();
            openPicker.ViewMode = PickerViewMode.Thumbnail;
            openPicker.SuggestedStartLocation = PickerLocationId.VideosLibrary;
            openPicker.FileTypeFilter.Add(".mp4");
            openPicker.FileTypeFilter.Add(".mkv");
            openPicker.FileTypeFilter.Add(".avi");
            openPicker.FileTypeFilter.Add(".mov");

            StorageFile file = await openPicker.PickSingleFileAsync();
            if (file != null)
            {
                //var uri = new Uri(file.Path, UriKind.Absolute);
                var uri = new Uri(file.Path);
                VlcElement.Source = uri;
                VlcElement.Play();
            }
        }

**Comment by kakone** [comment]
You are right, there is a bug in the MediaElement and it's missing the libaccess_winrt_plugin.dll file in the libVLCX nuget package. I will correct this as soon as possible.

**Comment by Noemata** [comment]
Thanks a bunch.  I'm looking forward to using this since it will resolve some key limitations with the built in MediaElement capabilities.  Have you tried this on ARM, and if so is everything working?  Nice work!

**Comment by Noemata** [comment]
Could you please provide an ETA on this issue?

**Comment by roman-76** [comment]
@Noemata I had same issue in my test project. Try to open nuget package manager and update to Microsoft.NETCore.UniversalWindowsPlatform package to version 5.2.2.

**Comment by kakone** [comment]
Fixed in [version 0.9.9](https://www.nuget.org/packages/VLC.MediaElement/0.9.9).

**Comment by Noemata** [comment]
Thank you.
