### ISSUE TITLE
Track position change event?

### ISSUE THREAD

**Issue by JunielKatarn** [kakone/VLC.MediaElement#71]
Is there a way to programmatically tracks the position (time) of the media being currently played.

Can this information be accessed in a VLC.Mediaelement?
By looking at the code, seems that the `OnPositionChanged` event is private.

**Comment by Weissu** [comment]
I wish to get `OnPositionChanged` or similar. This event is very important. Now have to use really dirty trick to make sure if video has completed seek operation.

**Comment by kakone** [comment]
You can use the [RegisterPropertyChangedCallback ](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.dependencyobject.registerpropertychangedcallback)with the [Position](https://github.com/kakone/VLC.MediaElement/blob/84c0b5dbc3208850122b2cbb72eda664bb4655d4/VLCMediaElement/MediaElement.cs#L163) dependency property.

**Comment by Weissu** [comment]
[RegisterPropertyChangedCallback](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.dependencyobject.registerpropertychangedcallback) isn't exactly what I was looking for but with that I solved the problem anyway. Thanks for answering my problem.
