### ISSUE TITLE
Using ShowLoginDialog

### ISSUE THREAD

**Issue by arc95** [kakone/VLC.MediaElement#73]
Hi @kakone, I need to pass credentials to the video stream that's being opened. I saw [this issue](https://github.com/kakone/VLC.MediaElement/issues/45), where it talks about listening to `ShowLoginDialog` and subscribing to it. I'm looking at the sample app and wondering where I would do this. Can you provide an example code of how to do this? Thanks.

**Comment by arc95** [comment]
Thanks, @nograx. Sorry for my beginner question, but is it possible in that handler to prevent the dialog from appearing to the user so we just give the video the necessary credentials seamlessly? Thanks 👍

**Comment by nograx** [comment]
The Event is called "ShowLoginDialog", but no dialog will be shown at all. Just use the code above and provice your credentials with Username and Password.
