### ISSUE TITLE
No video after source changed

### ISSUE THREAD

**Issue by RobbyRobbyRobby** [kakone/VLC.MediaElement#8]
Hi,

I've got an ObservableCollection of objects containing, among other things, url's to video files.

I've got a view which browses through this collection, binding the SOURCE property of the VLC.MediaElement.

On ARM, it works perfectly.

On x86 however, only the first item in the collection works properly.  As soon as you move to the next object, it plays with sound only but the video is blank.

**Comment by kakone** [comment]
I couldn't reproduce this problem, it works for me. Please share a sample code that reproduces the bug.

**Comment by RobbyRobbyRobby** [comment]
I've remove the binding and MVVM.   This is just accessing two WEBM's.  Press the button and it changes the source property.

            <Button Content="Next" Tapped="Button_Tapped" />
            <vlc:MediaElement 
                x:Name="mediaElement"
                    AreTransportControlsEnabled="True"
                    Source="{Binding Current, Mode=OneWay}"
                    />
        </StackPanel>

public sealed partial class MediaBindingTestView : Page
    {
        //private myList list;

        public MediaBindingTestView()
        {
            this.InitializeComponent();
            mediaElement.AutoPlay = true;
            mediaElement.Source = "http://i.4cdn.org/3/1487389588380.webm";
        }

        private void Button_Tapped(object sender, TappedRoutedEventArgs e)
        {
            mediaElement.Stop();
            mediaElement.Source = "http://i.4cdn.org/3/1486312909231.webm";
        }

    }

**Comment by kakone** [comment]
There is a problem with your sample because `http://i.4cdn.org/3/1486312909231.webm` returns a 404 error, but otherwise, with another WEBM file, it works well.

**Comment by kakone** [comment]
You can try with current version, I think it's fixed.
