### ISSUE TITLE
Is Winform Support Planned ?

### ISSUE THREAD

**Issue by graysuit** [kakone/VLC.MediaElement#88]
Is Winform Support Planned ?
Although I already designed all libvlc controls for winform,
But I wanted to see your controls,
As you are experinced and old one.

**Comment by kakone** [comment]
No, Winforms will not be supported (not enough time), and the updates will now be done in [LibVLCSharp](https://github.com/videolan/libvlcsharp) project (I'm going to close this repository soon in favor of LibVLCSharp).
A VLC MediaPlayerElement now exists in Xamarin.Forms, UWP, and Uno platform. For desktop apps, the next step will be to do a VLC MediaPlayerElement for WinUI 3.0, but I have nothing planned for Windows Forms.

**Comment by graysuit** [comment]
I have experience for making winform UI media player element,
so if I have free time i will make it for libvlcsharp,
Well Thanks for your time,
I loved your contribution for MediaPlayerElement specially for android. Thanks.

**Comment by kakone** [comment]
Yes, pull requests are welcome on LibVLCSharp and if you need any help, feel free to reach out to us on [Discord](https://discord.gg/3h3K3JF).

**Comment by graysuit** [comment]
Yeah I am already in,
Both Jeremy and Martin are very helpful for me,
I will soon try to make a Winform MediaPlayerElement demo.

I heard that UNO platform will replace winform,
This full setence I read from any where,
**WinForm was officially declared dead by Microsoft in 2014**
Is that right ? What do you think ?

**Comment by kakone** [comment]
It is certain that Winforms is no longer widely used, but I don't think it will be abandoned soon. The best proof is that it will be present in .Net 5 with a new designer. Uno will not replace it, the future of desktop applications in Windows is WinUI 3.0.

**Comment by graysuit** [comment]
WinUI as the name indicates UI,
So that's mean it is specially designed for UI,
Is it currently present or will be released ?
