### ISSUE TITLE
File access fault: Closer, but now we have a file access fault.

### ISSUE THREAD

**Issue by Noemata** [kakone/VLC.MediaElement#9]
Please create a file picker example for yourself, rather than playing videos from the Apps installation folder to see the following issue:

Exception thrown at 0x75A5A832 in SampleApp.exe: Microsoft C++ exception: Platform::AccessDeniedException ^ at memory location 0x0ED3F900. HRESULT:0x80070005 Access is denied.

WinRT information: Cannot access the specified file or folder (C:\Users\joeblow\Videos\big_buck_bunny_480p_surround-fix.avi). The item is not in a location that the application has access to (including application data folders, folders that are accessible via capabilities, and persisted items in the StorageApplicationPermissions lists). Verify that the file is not marked with system or hidden file attributes.

Create a button on the main form as follows:

<Page
    x:Class="SampleApp.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:SampleApp"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:vlc="using:VLC"
    mc:Ignorable="d">

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>

        <vlc:MediaElement x:Name="VlcElement" AreTransportControlsEnabled="True" HardwareAcceleration="True"
                          Source="http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_surround-fix.avi">
            <vlc:MediaElement.TransportControls>
                <vlc:MediaTransportControls ControlPanelOpacity="0.8"  />
            </vlc:MediaElement.TransportControls>
        </vlc:MediaElement>
        <Button Grid.Row="1" Content="Load" Click="OnClick" />
    </Grid>
</Page>

With code behind as follows:

using System;
using Windows.Media.Core;
using Windows.Storage;
using Windows.Storage.Pickers;
using Windows.UI.Xaml.Controls;

// The Blank Page item template is documented at http://go.microsoft.com/fwlink/?LinkId=402352&clcid=0x409

namespace SampleApp
{
    /// <summary>
    /// An empty page that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
        }

        private async void OnClick(object sender, Windows.UI.Xaml.RoutedEventArgs e)
        {
            // Create and open the file picker
            FileOpenPicker openPicker = new FileOpenPicker();
            openPicker.ViewMode = PickerViewMode.Thumbnail;
            openPicker.SuggestedStartLocation = PickerLocationId.VideosLibrary;
            openPicker.FileTypeFilter.Add(".mp4");
            openPicker.FileTypeFilter.Add(".mkv");
            openPicker.FileTypeFilter.Add(".avi");
            openPicker.FileTypeFilter.Add(".mov");

            StorageFile file = await openPicker.PickSingleFileAsync();
            if (file != null)
            {
                //var uri = new Uri(file.Path, UriKind.Absolute);
                var uri = new Uri(file.Path);
                VlcElement.Source = uri;
                VlcElement.Play();
            }
        }
    }
}

Playing from the Apps folder is the easier case.  Looking at the internals, I see that full paths are used rather than leveraging the FilePicker object.  The only way to make absolute paths work is to leverage the "Windows.Storage.AccessCache.StorageApplicationPermissions.FutureAccessList" API which isn't something you want to be doing behind the scenes, since I might not necessarily want my app to be adding to the FutureAccessList without knowing about it.  The WinRT VLC player must have a solution for this since it supports FilePicker usage.

**Comment by Noemata** [comment]
Just a thought, you can avoid all file access related problems by always using a stream, and let the stream get establish higher up in the API layer.  There really is no need for the lower layer to have any notion of a file.

**Comment by kakone** [comment]
I think you will understand the problem, I can't manage the files access because all the work is done by libVLC. I can just pass a string URI.  The WinRT VLC player use `StorageApplicationPermissions.FutureAccessList` to resolve this problem. In fact, you can pass the token in libVLC with a `winrt://` prefix, like this :
```
var file = await openPicker.PickSingleFileAsync();
if (file != null)
{
   VlcElement.Source = $"winrt://{StorageApplicationPermissions.FutureAccessList.Add(file)}";
}
```

**Comment by Noemata** [comment]
I now understand the problem.  I had a feeling the solution would be something like this.  I can see a workaround where you would check the contents of the FutureAccessList, add an entry if not present and remove it after a file has started playing, but that is rather messy.  The FutureAccessList approach should only be considered a workaround until a more correct approach is resolved.  The intent of the FutureAccessList is to allow the App and user to control what gets assigned permanent access to the App.  Its purpose is diluted if we assign access to everything that gets touched during file selection.

**Comment by kakone** [comment]
Yes, the FutureAccessList approach is a workaround but VLC was written for desktop applications, so they did some tricks in order to make it work for WinRT. In practice, you can give access only to the latest played file with `StorageApplicationPermissions.FutureAccessList.AddOrReplace(FILE_TOKEN, file); // FILE_TOKEN is a GUID in registry format`.

Now, Source property is not an URI but a string, because there is a problem with URIs that contains an username and a password (http://user:pass@xyz). It's strange but binding doesn't work with this kind of URI (there is a security exception).
